### ISSUE TITLE
celeryd.log : Error ketika memproses form images

### ISSUE THREAD

**Issue by wildanm** [openthinklabs/SmartOMR#5]
[2014-03-06 19:07:50,858: INFO/MainProcess] Received task: ODKScan_webapp.tasks.process_image[5bca1694-0bf2-48ec-98db-5f512dacc40c]
[2014-03-06 19:07:50,860: WARNING/Worker-1] ODKScan_webapp.tasks.process_image[5bca1694-0bf2-48ec-98db-5f512dacc40c]: test
[2014-03-06 19:07:50,984: INFO/MainProcess] Received task: ODKScan_webapp.tasks.process_image[8bfc8b7a-9f44-4d98-8936-a93d9620a368]
/usr/local/lib/python2.7/dist-packages/celery/app/trace.py:343: RuntimeWarning: Exception raised outside body: TypeError("_store_result() got an unexpected keyword argument 'request'",):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 262, in trace_task
    uuid, retval, SUCCESS, request=task_request,
  File "/usr/local/lib/python2.7/dist-packages/celery/backends/base.py", line 223, in store_result
    request=request, **kwargs)
TypeError: _store_result() got an unexpected keyword argument 'request'

  exc, exc_info.traceback)))

**Comment by wildanm** [comment]
Sepertinya ini masalah permission, ketika permission di webapps/scan_admin/media diset 0777 recursice, proses bisa berjalan, meskipun ketika dalam proses tetap muncul seperti itu, lagi-lagi sepertinya ini masalah di permission.
